// Generated by typings
// Source: https://raw.githubusercontent.com/aurelia/validatejs/master/dist/aurelia-validatejs.d.ts
declare module 'aurelia-validatejs' {
import {
  metadata
} from 'aurelia-metadata';
import {
  ValidationError,
  Validator as ValidatorInterface
} from 'aurelia-validation';
//import validate from 'validate.js';
export const metadataKey: any;
export class ValidationRule {
  name: any;
  config: any;
  constructor(name?: any, config?: any);
  static date(config?: any): any;
  static datetime(config?: any): any;
  static email(config?: any): any;
  static equality(config?: any): any;
  static exclusion(config?: any): any;
  static format(config?: any): any;
  static inclusion(config?: any): any;
  static lengthRule(config?: any): any;
  static numericality(config?: any): any;
  static presence(config?: any): any;
  static url(config?: any): any;
}
export function cleanResult(data?: any): any;
export class ValidationRules {
  rules: any;
  static ensure(prop?: any): any;
  on(target?: any): any;
  decorate(): any;
  addRule(key?: any, rule?: any): any;
  ensure(prop?: any): any;
  length(configuration?: any): any;
  presence(configuration?: any): any;
  required(configuration?: any): any;
  numericality(configuration?: any): any;
  date(configuration?: any): any;
  datetime(configuration?: any): any;
  email(configuration?: any): any;
  equality(configuration?: any): any;
  format(configuration?: any): any;
  inclusion(configuration?: any): any;
  exclusion(configuration?: any): any;
  url(configuration?: any): any;
}
export function base(targetOrConfig?: any, key?: any, descriptor?: any, rule?: any): any;
export function addRule(target?: any, key?: any, descriptor?: any, targetOrConfig?: any, rule?: any): any;
export function length(targetOrConfig?: any, key?: any, descriptor?: any): any;
export function presence(targetOrConfig?: any, key?: any, descriptor?: any): any;
export function required(targetOrConfig?: any, key?: any, descriptor?: any): any;
export function date(targetOrConfig?: any, key?: any, descriptor?: any): any;
export function datetime(targetOrConfig?: any, key?: any, descriptor?: any): any;
export function email(targetOrConfig?: any, key?: any, descriptor?: any): any;
export function equality(targetOrConfig?: any, key?: any, descriptor?: any): any;
export function exclusion(targetOrConfig?: any, key?: any, descriptor?: any): any;
export function inclusion(targetOrConfig?: any, key?: any, descriptor?: any): any;
export function format(targetOrConfig?: any, key?: any, descriptor?: any): any;
export function url(targetOrConfig?: any, key?: any, descriptor?: any): any;
export function numericality(targetOrConfig?: any, key?: any, descriptor?: any): any;
export class Validator {
  validateProperty(object?: any, propertyName?: any, rules?: any): any;
  validateObject(object?: any, rules?: any): any;
}
export function configure(config?: any): any;
}
