// Generated by typings
// Source: https://raw.githubusercontent.com/aurelia/fetch-client/bbe0777ef710d889a05759a65fa2c9c3865fc618/doc/url.d.ts
declare class URLSearchParams {
	append(name: string, value: string): void;
	delete(name: string):void;
	get(name: string): string;
	getAll(name: string): Array<string>;
	has(name: string): boolean;
	set(name: string, value: string): void;
}
